#+TITLE: Rammel
#+AUTHOR: Bryce Carson

* Grok help                                                         :ARCHIVE:
*Minimal changes needed:*

- Use POSIX-style paths (=/=) and Unix commands (=rm=, =mkdir=, etc.).
  No accommodation for Windows =\= separators required.

- Detect environment if needed:

  #+begin_src make
  ifeq ($(OS),Windows_NT)
    # optional Windows-specific rules
  else
    # POSIX (MSYS2)
  endif
  #+end_src

- For executables: add =.exe= suffix when targeting native MinGW builds
  (e.g., =TARGET = myprog$(EXE)= where =EXE=.exe= on Windows).

MSYS2 make in Git for Windows SDK behaves like Unix make.

* Dependencies                                                      :ARCHIVE:
On Windows, building requires the full /Git for Windows SDK/ installed, not just
/Git for Windows/. This allows Windows users to use MSYS2 to build Arch
packages, in particular the =make= package with Guile support. =make= on MSYS2
enables native Windows development using GNU Make makefiles without compromising
on syntax or overusing text replacement macros to provide compatibility with
Windows path separators and other oddities.

Everything I was writing in Premake is moving back into Make, but with the Guile
feature so I can rewrite the helper functions I wrote in Lua in Guile and use
that to simplify the makefile.

Make supports Guile Scheme as an embedded extension language since version 4.0,
but many distributions do not build Make with this feature by default.

*** Fedora
Fedora no longer builds /GNU make/ with Guile enabled by default, so I needed to
rebuild the package with the Guile feature enabled.

#+begin_src bash
  dnf download --srpm make
  dnf install 'pkgconfig(guile-3.0)' perl# perhaps also perl-devel and guile-devel
  rpmbuild -ba make.spec --with guile
  rpmbuild -ba --with guile
#+end_src

*** Arch & Windows (with the /Git for Window SDK/)
The full SDK version of Git for Windows shall be required, as the new
makefile utilizes GUILE to simplify some build steps that were
difficult.

1. =pacman -S --needed base-devel guile-devel=.
2. =git clone https://github.com/msys2/MSYS2-packages.git && cd MSYS2-packages/make=.
3. Edit =PKGBUILD=: remove =--without-guile= (or add =--with-guile=) from =configure= line.
4. =makepkg -s --noconfirm=.
5. =pacman -U make-*.pkg.tar.zst=.

* About
This is a working file only. It is not documentation for Rammel.

#+begin_quote
With this change you will have .cfg files for configuration and shared
functions, .nws files for stages and internal filters, and extensionless files
for commands.
#+end_quote

It's my goal to edify myself by translating into Lua 5.5 the filters and stages
which were previously translated by Zitzelsberger from lua2.5+nw into Lua 3.

I will be calling this derived work Rammel. In the future, especially if all
development goals are met, I'll send Ramsey another postcard to ask about
calling it noweb and getting the changes merged.

* Makefiles
These makefiles direct the compilation of the two main targets, /no/ and
/nwmtime/, from C and Lua sources utilizing CII and one of three versions of the
Lua language.

** Top-level
The top-level makefile parses the make command-line options and validates them.

#+begin_src makefile :noweb no-export :tangle src/Makefile
  srcdir ?= .

  ## System calls
  PIPE ?= fork

  ## Paths
  BIN ?= /usr/bin
  LIBEXEC ?= /usr/libexec/rammel
  TEXINPUTS ?= /usr/share/texlive/texmf-local/tex/latex/rammel
  SHELL ?= /usr/bin/bash

  ## Compiler, linker-loader, and archiver options
  ## Compiler
  CC ?= gcc
  CFLAGS ?= -ansi -pedantic -std=c11 -c
  XCFLAGS ?= 
  CPPFLAGS ?= -DNWDEFAULTDIR=\"'$(LIBEXEC)'\" -DPLATFORM='$(PLATFORM)' -DPOSIX -D_POSIX_SOURCE -Dnw_unix
  ## Linker-loader
  LD ?= gcc
  LIBPROLOGUE ?= 
  LDFLAGS ?= -lc
  LIBEPILOGUE ?= 

  ## Archiver
  AR ?= ar
  RANLIB ?= ranlib

  CIIMAXALIGN ?= 

  XINCLUDES ?= 

  POPEN ?= 
  POSIX ?= 
  STRERROR ?= 

  ## These are built-in make variables, and may as well be overridden with noweb
  ## variants (when not initialized as more).
  TANGLE ?= more
  WEAVE ?= noweave
  PLATFORM ?= "unix"

  ## INSTALL* is recommended by the GNU Coding Standards, and is extremely
  ## prevalent. It also enables a more maintainable Makefile.
  INSTALL ?= install
  INSTALL_PROGRAM ?= $(INSTALL)
  INSTALL_DATA ?= $(INSTALL) -m 644

  BUILDDIR ?= $(srcdir)/../build
  VPATH  ?= $(BUILDDIR)

  BUILD_EXEC ?= $(BUILDDIR)$(LIBEXEC)
  BUILD ?= $(srcdir)/mkinstalldirs | $(BUILD_EXEC)

  NOCOND ?= $(BUILD_EXEC)/tools/nocond

  LUA_VERSION = 2

  # Stop editing. No user-serviceable parts below.
  .EXPORT_ALL_VARIABLES :
  .PHONY : help transfer install pdf

  help :
  	@echo "PIPE (by default, \"$(PIPE)\"): What system call should Rammel use? fork | pipe"
  	@echo "BIN (by default, \"$(BIN)\"): The installation location for user programs."
  	@echo "LIBEXEC (by default, \"$(LIBEXEC)\"): The installation location for programs used only by user programs."
  	@echo "TEXINPUTS (by default, \"$(TEXINPUTS)\"): The installation location for LaTeX and TeX style and class files."
  	@echo "SHELL (by default, \"$(SHELL)\"): The shell to use when invoking recipe rules."
  	@echo "CC (by default, \"$(CC)\"): The command to invoke a C compiler."
  	@echo "CFLAGS (by default, \"$(CFLAGS)\"): C compilation flags."
  	@echo "XCFLAGS (by default, \"$(XCFLAGS)\"): Additional C compilation flags specific to the compilation of no''"
  	@echo "LD (by default, \"$(LD)\"): The command to invoke a C linker-loader."
  	@echo "LIBPROLOGUE (by default, \"$(LIBPROLOGUE)\"): Anything that should precede LDFLAGS when invoking the linker-loader."
  	@echo "LDFLAGS (by default, \"$(LDFLAGS)\"): C linker-loader flags."
  	@echo "LIBEPILOGUE (by default, \"$(LIBEPILOGUE)\"): Anything that should succeed LDFLAGS when invoking the linker-loader."
  	@echo "AR (by default, \"$(AR)\"): The command to invoke a C archiver."
  	@echo "RANLIB (by default, \"$(RANLIB)\"): The command to invoke ranlib."
  	@echo "CIIMAXALIGN (by default, \"$(CIIMAXALIGN)\"): The value for maximum alignment used when compiling CII; see CIIs index.html for more information."
  	@echo "XINCLUDES (by default, \"$(XINCLUDES)\"): Additional libraries to include when compiling the no' command.'"
  	@echo "POPEN (by default, \"$(POPEN)\"): TODO: document this option."
  	@echo "POSIX (by default, \"$(POSIX)\"): Whether or not this system is POSIX-compliant."
  	@echo "STRERROR (by default, \"$(STRERROR)\"): TODO: document this option."

  all : code scripts styles

  installdirs : $(srcdir)/mkinstalldirs
  	$(srcdir)/mkinstalldirs $(DESTDIR)$(LIBEXEC) $(TEXINPUTS)

  $(BUILD_EXEC) : $(srcdir)/mkinstalldirs
  	$(srcdir)/mkinstalldirs $(addprefix $(BUILD_EXEC)/,tools cii lua-2.5.1 lua-3.2.2 c lua tex)

  tools : $(BUILD)
  	$(MAKE) -C $(srcdir)/tools "OUTPUT=$(BUILD_EXEC)/tools"

  ciilib : $(BUILD)
  	$(MAKE) -C $(srcdir)/cii "OUTPUT=$(BUILD_EXEC)/cii"

  lualib : $(BUILD)
  	$(MAKE) -C $(srcdir)/lua-2.5.1 "OUTPUT=$(BUILD_EXEC)/lua-2.5.1"

  lualib3 : $(BUILD)
  	$(MAKE) -C $(srcdir)/lua-3.2.2 "OUTPUT=$(BUILD_EXEC)/lua-3.2.2"

  TANGLEOPTS = " | $(addprefix $(BUILD_EXEC)/tools/,markup nt)"
  code: TANGLEOPTS = " | $(NOCOND) lua2 | $(NOCOND) $(PIPE) $(TANGLEOPTS)"
  code : tools ciilib lualib
  	$(MAKE) -C $(srcdir)/c                      \
          "NOTANGLE=more"                       \
          "TANGLEOPTS= $(TANGLEOPTS)"           \
          "CPIF=>"                              \
          "TOOLS=$(BUILD_EXEC)/tools"           \
          "LUA=../$(LUA_VERSION)"               \
          "LUALIB=$(BUILD_EXEC)/$(LUA_VERSION)" \
          "OUTPUT=$(BUILD_EXEC)/c"

  scripts: TANGLEOPTS = " | $(NOCOND) lua2 | $(NOCOND) $(PIPE) $(TANGLEOPTS)"
  scripts : tools
  	$(MAKE) -C $(srcdir)/lua "NOTANGLE=more" "TANGLEOPTS=$(TANGLEOPTS)" "CPIF=>" "OUTPUT=$(BUILD_EXEC)/lua"

  styles : tools
  	$(MAKE) -C $(srcdir)/../docs/tex "NOTANGLE=more" "TANGLEOPTS=$(TANGLEOPTS)" "CPIF=>" "OUTPUT=$(BUILD_EXEC)/tex"

  careful :
  	$(MAKE) clobber all clean
  	-$(RMDIR) $(BUILD_EXEC)/first
  	mkdir $(addprefix $(BUILD_EXEC)/,first first/c first/lua first/tex)
  	cp -R $(BUILD_EXEC)/c/* $(BUILD_EXEC)/first/c
  	cp -R $(BUILD_EXEC)/lua/* $(BUILD_EXEC)/first/lua
  	cp -R $(BUILD_EXEC)/tex/* $(BUILD_EXEC)/first/tex

  	$(MAKE) clobber tools ciilib lualib
  	-mkdir $(BUILD_EXEC)/c
  	$(MAKE) -C $(srcdir)/c "NWPATH=$(LIBEXEC)/first/lua" "NOTANGLE=more" "TANGLEOPTS= | $(NOCOND) lua2 | $(NOCOND) $(PIPE) | $(LIBEXEC)/first/c/no tangle" "CPIF=>" "TOOLS=$(LIBEXEC)/tools" "LUA=../lua-2.5" "LUALIB=$(LIBEXEC)/lua-2.5" "OUTPUT=$(BUILD_EXEC)/c"

  	-mkdir $(LIBEXEC)/lua
  	$(MAKE) -C $(srcdir)/lua "NWPATH=$(LIBEXEC)/first/lua" "NOTANGLE=$(LIBEXEC)/first/c/no tangle" "TANGLEOPTS=" "CPIF=>" "OUTPUT=$(BUILD_EXEC)/lua"

  	-mkdir $(LIBEXEC)/tex
  	$(MAKE) -C $(srcdir)/tex "NWPATH=$(LIBEXEC)/first/lua" "NOTANGLE=$(LIBEXEC)/first/c/no tangle" "TANGLEOPTS=" "CPIF=>" "OUTPUT=$(BUILD_EXEC)/tex"

  	@echo "At this point we are attempting to BUILD the literate version."
  	@echo "It may fail if you have not previously installed noweb.sty."

  	$(MAKE) -C $(srcdir)/c "NWPATH=$(LIBEXEC)/first/lua" "OUTPUT=$(BUILD_EXEC)/c" doc
  	-$(RMDIR) $(BUILD_EXEC)/first

  	$(MAKE) all clean





  define with_m_make_n
  $(foreach t,clobber tools ciilib $(if $(findstring "2",${2}),"lualib","lualib3"),$(MAKE) ${t})
  $(foreach d,$(addprefix $(BUILD_EXEC)/,c lua tex ${1}${2} ${1}${2}/c ${1}${2}/lua ${1}${2}/tex), mkdir ${d})
  $(MAKE) -C $(srcdir)/c "NWPATH=$(LIBEXEC)/${1}b/lua" "NOTANGLE=more" "TANGLEOPTS= | $(NOCOND) lua${2} | $(NOCOND) $(PIPE) | $(LIBEXEC)/${1}b/c/no tangle" "CPIF=>" "TOOLS=$(LIBEXEC)/tools" $(if $(findstring "2",$2),"LUA=../lua-2.5","LUA=../lua-3.0") $(if $(findstring "2",$2),"LUALIB=$(LIBEXEC)/lua-2.5","LUALIB=$(LIBEXEC)/lua-3.0") "OUTPUT=$(BUILD_EXEC)/c"
  $(MAKE) -C $(srcdir)/lua "NWPATH=$(LIBEXEC)/${1}b/lua" "NOTANGLE=more" "TANGLEOPTS= | $(NOCOND) lua${2} | $(LIBEXEC)/${1}b/c/no tangle" "CPIF=>" "OUTPUT=$(BUILD_EXEC)/lua"
  $(MAKE) -C $(srcdir)/tex "NWPATH=$(LIBEXEC)/${1}b/lua" "NOTANGLE=$(LIBEXEC)/${1}b/c/no tangle" "TANGLEOPTS=" "CPIF=>" "OUTPUT=$(BUILD_EXEC)/tex"
  $(MAKE) -C $(srcdir)/c doc "NWPATH=$(LIBEXEC)/lua" "OUTPUT=$(BUILD_EXEC)/c"
  $(foreach d,c lua tex,cp -R $(wildcard $(BUILD_EXEC)/${d}/*) $(BUILD_EXEC)/${1}${2}/${d})
  endef

  transfer:
  # noweb_2_11b->Rammel with Lua 2
  	$(MAKE) clobber all
  	$(MAKE) -C $(srcdir)/c "NWPATH=$(LIBEXEC)/lua" "OUTPUT=$(BUILD_EXEC)/c" doc
  	$(foreach d,$(addprefix $(BUILD_EXEC)/,2b 2b/c 2b/lua 2b/tex), mkdir ${d})
  	$(foreach d,c lua tex,cp -R $(wildcard $(BUILD_EXEC)/${d}/*) $(BUILD_EXEC)/2b/${d})



  # noweb_2_11b->Rammel with Lua 3
  	$(foreach t,clobber tools ciilib lualib3,$(MAKE) ${t})
  	$(foreach d,$(addprefix $(BUILD_EXEC)/,c lua tex 3b 3b/c 3b/lua 3b/tex), mkdir ${d})
  	$(MAKE) -C $(srcdir)/c "NOTANGLE=more" "TANGLEOPTS= | $(NOCOND) lua3 | $(NOCOND) $(PIPE) | $(LIBEXEC)/tools/markup | $(LIBEXEC)/tools/nt" "CPIF=>" "TOOLS=$(LIBEXEC)/tools" "LUA=../lua-3.0" "LUALIB=$(LIBEXEC)/lua-3.0" "OUTPUT=$(BUILD_EXEC)/c"
  	$(MAKE) -C $(srcdir)/lua "NOTANGLE=more" "TANGLEOPTS= | $(NOCOND) lua3 | $(LIBEXEC)/tools/markup | $(LIBEXEC)/tools/nt" "CPIF=>" "OUTPUT=$(BUILD_EXEC)/lua"
  	$(MAKE) -C $(srcdir)/tex "NOTANGLE=more" "TANGLEOPTS= | $(LIBEXEC)/tools/markup | $(LIBEXEC)/tools/nt" "CPIF=>" "OUTPUT=$(BUILD_EXEC)/tex"
  	$(MAKE) -C $(srcdir)/c doc "NWPATH=$(LIBEXEC)/lua" "OUTPUT=$(BUILD_EXEC)/c"
  	$(foreach d,c lua tex,cp -R $(wildcard $(BUILD_EXEC)/${d}/*) $(BUILD_EXEC)/3b/${d})



  	$(call with_m_make_n,2,2)# Rammel with Lua 2->Rammel with Lua 2
  	$(call with_m_make_n,2,3)# Rammel with Lua 2->Rammel with Lua 3
  	$(call with_m_make_n,3,2)# Rammel with Lua 3->Rammel with Lua 2
  	$(call with_m_make_n,3,3)# Rammel with Lua 3->Rammel with Lua 3



  # check differences
  	$(MAKE) clean checkclean checkdifferent checksame





  checkclean :
  	@echo "Let's see how different it is..."
  	$(foreach clean_target,2b 22 23 3b 32 33,$(RM) $(addprefix $(BUILD_EXEC)/${clean_target}/c/,$(wildcard *.exe *.log *.obj *.dvi)))

  checkdifferent_fn=$(DIFF) $(foreach other,3b 32 33,$(BUILD_EXEC)/$1 $(BUILD_EXEC)/${other})
  checkdifferent :
  	$(foreach other,2b 22 23,$(call checkdifferent_fn, ${other}))

  checksame :
  	@echo "Let's see how similar it is..."
  	$(DIFF) $(BUILD_EXEC)/2b $(BUILD_EXEC)/22
  	$(DIFF) $(BUILD_EXEC)/22 $(BUILD_EXEC)/23
  	$(foreach other,3b 32,$(call checkdifferent_fn, ${other}))

  dvi :
  	@echo "Building the PDF may fail if you don't have no installed properly."
  	$(MAKE) -C $(srcdir)/c "OUTPUT=$(BUILD_EXEC)/c" dvi

  install : installdirs code scripts styles | $(if $(strip $(DESTDIR)$(BIN)),$(DESTDIR)$(BIN),$(error "$(BIN) doesn't exist!"))
  	$(INSTALL_PROGRAM) --target-directory $(DESTDIR)$(BIN) $(addprefix $(BUILD_EXEC)/c/,no nwmtime)
  	$(INSTALL_PROGRAM) --target-directory $(DESTDIR)$(LIBEXEC) $(wildcard $(BUILD_EXEC)/lua/*)
  	$(INSTALL_DATA) $(BUILD_EXEC)/tex/noweb.sty $(DESTDIR)$(TEXINPUTS)/noweb.sty
  	$(INSTALL_DATA) $(BUILD_EXEC)/tex/nwmac.tex $(DESTDIR)$(TEXINPUTS)/nwmac.tex

  clean :
  	$(MAKE) -C $(srcdir)/tools "OUTPUT=$(BUILD_EXEC)/tools" clobber
  	-$(RMDIR) $(BUILD_EXEC)/tools

  	$(MAKE) -C $(srcdir)/cii "OUTPUT=$(BUILD_EXEC)/cii" clobber
  	-$(RMDIR) $(BUILD_EXEC)/cii

  	$(MAKE) -C $(srcdir)/lua-2.5 $(LuaMakefile) "OUTPUT=$(BUILD_EXEC)/lua-2.5" clobber
  	-$(RMDIR) $(BUILD_EXEC)/lua-2.5

  	$(MAKE) -C $(srcdir)/c "OUTPUT=$(BUILD_EXEC)/c" clean
  	$(MAKE) -C $(srcdir)/lua "OUTPUT=$(BUILD_EXEC)/lua" clean
  	$(MAKE) -C $(srcdir)/tex "OUTPUT=$(BUILD_EXEC)/tex" clean
  	-$(RM) *~



  clobber : clean
  	$(MAKE) -C $(srcdir)/c "OUTPUT=$(BUILD_EXEC)/c" clobber
  	-$(RMDIR) $(BUILD_EXEC)/c

  	$(MAKE) -C $(srcdir)/lua "OUTPUT=$(BUILD_EXEC)/lua" clobber
  	-$(RMDIR) $(BUILD_EXEC)/lua

  	$(MAKE) -C $(srcdir)/tex "OUTPUT=$(BUILD_EXEC)/tex" clobber
  	-$(RMDIR) $(BUILD_EXEC)/tex
#+end_src

** DONE C
CLOSED: [2026-05-06 Wed 22:30]
This is the most important Makefile, other than the top-level makefile, as this
consumes the output of all the others: CII; an embeddable Lua; scripts written
in Lua.

PDF compilation fails.

Anyways, apparently =2= is the correct error code and something else is going on
with the system that is preventing it from loading noweb files properly,
especially =weave= or =tangle=! I need to compile the project with dubugging
symbols and see what is happening when =load_nwfile= is called.

#+begin_src makefile :tangle src/c/Makefile
  INCS = $(addprefix -I$(srcdir)/,c cii/include)

  ifeq ($(LUA_VERSION),2)
  LUA_VERSION=lua-2.5.1
  INCS += -I$(LUA_VERSION)
  else ifeq ($(LUA_VERSION),3)
  LUA_VERSION=lua-3.2.2
  INCS += -I$(LUA)/include
  else ifeq ($(LUA_VERSION),5)
  LUA_VERSION=lua-5.5.0
  else
  $(error "LUA_VERSION must be one of 2, 3, or 5.")
  endif

  NOOBJS=$(addprefix $(OUTPUT)/,$(addsuffix .o,columns cpif env-lua errors       \
  finduses fromascii getline ipipe ipipe-lua lua-help lua-main main markparse    \
  markup misc-lua modtrees modules mpipe mpipe-lua notangle noweb-lua nwbuffer   \
  nwbuffer-lua nwprocess nwtime recognize stages strsave sys util xpipe          \
  xpipe-lua))

  NWMTIMEOBJS=$(addprefix $(OUTPUT)/,$(addsuffix .o,columns errors getline nwmtime))

  # Sources to build when distributing C code (add all generated .c and .h files
  # to this list)
  SRCS = $(addprefix $(OUTPUT)/,cargs.h columns.c columns.h cpif.c cpif.h        \
  env-lua.c env-lua.h errors.c errors.h finduses.c fromascii.c fromascii.h       \
  getline.c getline.h ipipe-lua.c ipipe-lua.h ipipe.c ipipe.h lua-help.c         \
  lua-help.h lua-main.c lua-main.h main.c markparse.c markparse.h markup.c       \
  markup.h match.c match.h misc-lua.c misc-lua.h modtrees.c modtrees.h modules.c \
  modules.h mpipe-lua.c mpipe-lua.h mpipe.c mpipe.h notangle.c notangle.h        \
  noweb-lua.c noweb-lua.h nwbuffer-lua.c nwbuffer.c nwbuffer.h nwmtime.c         \
  nwprocess.c nwprocess.h nwtime.c nwtime.h precompiled.h recognize.c recognize.h\
  stages.c stages.h strsave.c strsave.h sys.c sys.h util.c util.h xpipe-lua.c    \
  xpipe-lua.h xpipe.c xpipe.h)

  CFLAGS += -g

  # Define a metarule so rules aren't needed for each object file.
  .c.o : ;
  	$(CC) $(INCS) $(CFLAGS) $(CPPFLAGS) -o $@ $*.c

  all : $(OUTPUT)/no $(OUTPUT)/nwmtime

  dvi : $(OUTPUT)/doc.tex $(OUTPUT)/allcode.tex
  	latexmk -output-directory=$(OUTPUT) $(OUTPUT)/doc.tex

  $(OUTPUT)/nwmtime : $(NWMTIMEOBJS)
  	$(CC) $(filter-out -c,$(CFLAGS)) $(CPPFLAGS) $(LDFLAGS) $(NWMTIMEOBJS) -o $@

  $(OUTPUT)/no: LIB = $(addprefix $(BUILD_EXEC)/,cii/libcii.so $(LUA_VERSION)/liblua.so $(LUA_VERSION)/liblualib.so)
  $(OUTPUT)/no : $(NOOBJS) $(LIB) $(BUILD_EXEC)/cii/memchk.o
  	$(CC) $(filter-out -c,$(CFLAGS)) $(XCFLAGS) $(CPPFLAGS) $(XINCLUDES) $(LDFLAGS) -lm $(NOOBJS) $(LIBPROLOGUE) $(LIB) $(LIBEPILOGUE) -o $@

  touch : $(SRCS)
  	touch $(SRCS)

  clean :
  	-$(RM) $(NOOBJS) $(NWMTIMEOBJS) $(SRCS) $(addprefix $(OUTPUT)/,$(wildcard nwbuffer-lua* allcode.tex doc.*))

  clobber : clean
  	-$(RM) $(addprefix $(OUTPUT)/,nwmtime no doc.pdf)

  $(OUTPUT)/doc.tex : doc.nw
  	cp doc.nw $@

  FILES = $(addsuffix .nw,columns cpif errors finduses getline ipipe ipipe-lua    \
  lua-main main markparse markup match modtrees modules mpipe mpipe-lua notangle  \
  nwbuffer nwmtime nwprocess nwtime recognize strsave xpipe                       \
  xpipe-lua)

  $(OUTPUT)/allcode.tex : $(FILES)
  	no weave -ifilter "Stages.elide, 'hackers:*'" -n -index $(FILES) > $@





  $(OUTPUT)/%.h : %.nw
  	$(NOTANGLE) $< $(TANGLEOPTS) -L$(subst SUBST,$<,"#line %L \"SUBST\"%N") -Rheader $(CPIF) $@

  $(OUTPUT)/%.c : %.nw
  	$(NOTANGLE) $< $(TANGLEOPTS) -L$(subst SUBST,$<,"#line %L \"SUBST\"%N") $(CPIF) $@

  $(OUTPUT)/nwbuffer-lua.c : nwbuffer.nw
  	$(NOTANGLE) $< $(TANGLEOPTS) -L$(subst SUBST,$<,"#line %L \"SUBST\"%N") -Rnwbuffer-lua.c $(CPIF) $@





  $(OUTPUT)/columns.o : $(addprefix $(OUTPUT)/,cargs.h columns.h columns.c)
  $(OUTPUT)/cpif.o : $(addprefix $(OUTPUT)/,cpif.h cpif.c errors.h strsave.h)
  $(OUTPUT)/env-lua.o : $(addprefix $(OUTPUT)/,env-lua.h lua-help.h)
  $(OUTPUT)/errors.o : $(addprefix $(OUTPUT)/,errors.c errors.h)
  $(OUTPUT)/finduses.o : $(addprefix $(OUTPUT)/,errors.h finduses.c getline.h match.h nwbuffer.h recognize.h)
  $(OUTPUT)/fromascii.o : $(addprefix $(OUTPUT)/,errors.h fromascii.c fromascii.h getline.h nwbuffer.h)
  $(OUTPUT)/getline.o : $(addprefix $(OUTPUT)/,columns.h errors.h getline.c getline.h)
  $(OUTPUT)/ipipe.o : $(addprefix $(OUTPUT)/,ipipe.c ipipe.h nwbuffer.h nwtime.h)
  $(OUTPUT)/ipipe-lua.o : $(addprefix $(OUTPUT)/,ipipe-lua.c ipipe-lua.h)
  $(OUTPUT)/lua-help.o : $(addprefix $(OUTPUT)/,lua-help.c lua-help.h)
  $(OUTPUT)/lua-main.o : $(addprefix $(OUTPUT)/,env-lua.h ipipe-lua.h lua-main.c lua-main.h misc-lua.h mpipe-lua.h noweb-lua.h stages.h util.h xpipe-lua.h)
  $(OUTPUT)/main.o : $(addprefix $(OUTPUT)/,cargs.h columns.h cpif.h errors.h main.c modtrees.h modules.h notangle.h nwbuffer.h)
  $(OUTPUT)/markparse.o : $(addprefix $(OUTPUT)/,columns.h errors.h getline.h markparse.c markparse.h markup.h nwbuffer.h)
  $(OUTPUT)/markup.o : $(addprefix $(OUTPUT)/,errors.h markup.c markup.h strsave.h)
  $(OUTPUT)/misc-lua.o : $(addprefix $(OUTPUT)/,lua-help.h misc-lua.c misc-lua.h)
  $(OUTPUT)/modtrees.o : $(addprefix $(OUTPUT)/,errors.h modtrees.c modtrees.h modules.h strsave.h)
  $(OUTPUT)/modules.o : $(addprefix $(OUTPUT)/,columns.h errors.h modtrees.h modules.c modules.h strsave.h)
  $(OUTPUT)/mpipe.o : $(addprefix $(OUTPUT)/,fromascii.h ipipe.h mpipe.c mpipe.h nwbuffer.h xpipe.h)
  $(OUTPUT)/mpipe-lua.o : $(addprefix $(OUTPUT)/,lua-help.h mpipe.h mpipe-lua.c mpipe-lua.h)
  $(OUTPUT)/notangle.o : $(addprefix $(OUTPUT)/,errors.h getline.h match.h modtrees.h modules.h notangle.c notangle.h nwbuffer.h strsave.h)
  $(OUTPUT)/noweb-lua.o : $(addprefix $(OUTPUT)/,lua-help.h noweb-lua.c noweb-lua.h util.h)
  $(OUTPUT)/nwbuffer.o : $(addprefix $(OUTPUT)/,nwbuffer.c nwbuffer.h)
  $(OUTPUT)/nwbuffer-lua.o : $(addprefix $(OUTPUT)/,lua-help.h nwbuffer.h nwbuffer-lua.c)
  $(OUTPUT)/nwmtime.o : $(addprefix $(OUTPUT)/,getline.h nwmtime.c)
  $(OUTPUT)/nwprocess.o : $(addprefix $(OUTPUT)/,nwprocess.c nwprocess.h)
  $(OUTPUT)/nwtime.o : $(addprefix $(OUTPUT)/,nwtime.c nwtime.h)
  $(OUTPUT)/recognize.o : $(addprefix $(OUTPUT)/,recognize.c)
  $(OUTPUT)/stages.o : $(addprefix $(OUTPUT)/,cargs.h fromascii.h lua-help.h markparse.h notangle.h nwbuffer.h stages.c stages.h)
  $(OUTPUT)/strsave.o : $(addprefix $(OUTPUT)/,errors.h strsave.c strsave.h)
  $(OUTPUT)/sys.o : $(addprefix $(OUTPUT)/,sys.c sys.h)
  $(OUTPUT)/util.o : $(addprefix $(OUTPUT)/,precompiled.h sys.h util.c util.h)
  $(OUTPUT)/xpipe.o : $(addprefix $(OUTPUT)/,errors.h nwprocess.h sys.h util.h xpipe.c xpipe.h)
  $(OUTPUT)/xpipe-lua.o : $(addprefix $(OUTPUT)/,cargs.h lua-help.h xpipe.h xpipe-lua.c xpipe-lua.h)
#+end_src

To build /no/ and /nwmtime/, the two projects that comprise the Rammel, H and C
files must first be tangled from their noweb sources.

** DONE Lua
CLOSED: [2026-05-03 Sun 20:18]
#+begin_src makefile :tangle src/lua/Makefile :noweb no-export
  CONFIG = $(addprefix $(OUTPUT)/,pipes.cfg sys.cfg noweb.cfg util.cfg list.nws set.nws)
  FILTERS = $(addprefix $(OUTPUT)/,cat.nws stripconds.nws xchunks.nws lines.nws)
  STAGES = $(addprefix $(OUTPUT)/,totex.nws tohtml.nws noidx.nws elide.nws unmarkup.nws) $(FILTERS)
  SCRIPTS = $(addprefix $(OUTPUT)/,tangle weave)

  .PHONY : all clean clobber install

  all : $(CONFIG) $(STAGES) $(SCRIPTS)

  clean :

  clobber : clean
  	-$(RM) $(CONFIG) $(FILTERS) $(STAGES) $(SCRIPTS)

  ## LIB2 is the directory where external stanges from Noweb 2 are located; LIB3
  ## is where stages of Noweb 3 are located. LIB2 and LIB3 do not relate to Lua 2
  ## or Lua 3.
  install : $(SCRIPTS) $(CONFIG) $(STAGES)
  	for i in $(CONFIG) $(STAGES); do                    \
        sed 's@|LIBDIR|@$(LIB2)@g' $$i > $(OUTPUT)/$$i; \
    done
  	for i in $(SCRIPTS); do                       \
        cp $$i $(OUTPUT)/`basename $$i .nws`;     \
    done

  $(OUTPUT)/%.cfg : config.nw
  	$(NOTANGLE) $< $(TANGLEOPTS) -R$(@F) $(CPIF) $@

  $(OUTPUT)/%.nws : %.nw
  	$(NOTANGLE) $< $(TANGLEOPTS) $(CPIF) $@

  $(OUTPUT)/tangle : tangle.nw
  	$(NOTANGLE) tangle.nw $(TANGLEOPTS) $(CPIF) $@

  $(OUTPUT)/weave : weave.nw
  	$(NOTANGLE) weave.nw $(TANGLEOPTS) $(CPIF) $@

  $(OUTPUT)/noidx.tex: noidx.nw
  	which no
  	no weave -delay -x -filter 'elide hackers:*' noidx.nw > $@

  # <<test and htmltest>>
#+end_src

*** TODO Test Lua NWS files and test an HTML file of unknown structure and unavailable origin
Norman Ramsey does not make available the WWW, and the NWS test requires that
the scripts be tangled to this directory, which they aren't at present.

#+name: test and htmltest
#+begin_src makefile :noweb yes
  <<lua-test-nws>>

  <<lua-test-html>>
#+end_src

Test the script files in the current directory:

#+name: lua-test-nws
#+begin_src makefile
  # TODO: requires tangling to the current directory; which I'm not doing right now.
  test: $(CONFIG) $(STAGES) $(SCRIPTS)
  	@echo 'write("Scripts load from .\n")' | NWPATH=. no
  	@echo 'argv = {"-internaldefaults", "-n", "-html", "/dev/null"}; do_nwfile("weave.nws"); write("Null weave OK.\n")' | NWPATH=. no
  	@echo 'argv = {"-internal", "test.nw"}; do_nwfile("tangle.nws"); write("Null tangle OK.\n")' | NWPATH=. no
#+end_src

Test an HTML file of unknown structure:

#+name: lua-test-html
#+begin_src makefile
  # TODO: requires an HTML file of unknown structure.
  htmltest: $(CONFIG) $(STAGES) $(SCRIPTS)
  	@echo 'testfile("/home/nr/www/noweb/index.html")' | NWPATH=. no
#+end_src

** Formal Tests
Two tests were defined in the original Makefile, one for the functionality of the Lua sources and one for the HTML.

#+begin_src makefile
  test: $(CONFIG) $(STAGES) $(SCRIPTS)
        @echo 'write("Scripts load from .\n")' | NWPATH=. no
        @echo 'argv = {"-internaldefaults", "-n", "-html", "/dev/null"}; do_nwfile("weave.nws"); write("Null weave OK.\n")' | NWPATH=. no
        @echo 'argv = {"-internal", "test.nw"}; do_nwfile("tangle.nws"); write("Null tangle OK.\n")' | NWPATH=. no
#+end_src

The first test ensures that =no= can load scripts from the current directory.
The envvar =NWPATH= was set to =.=, the current directory, and =no= called with
it standard input from the =@echo= lines.

#+begin_src lua
  write("Scripts load from .\n");
  argv = { "-internaldefaults", "-n", "-html", "/dev/null" }; do_nwfile("weave.nws"); write("Null weave OK.\n");
  argv = { "-internal", "test.nw" }; do_nwfile("tangle.nws"); write("Null tangle OK.\n");
#+end_src

** DONE Tools
CLOSED: [2026-05-03 Sun 01:21]
These tools are used to bootstrap Rammel by tangling its sources from noweb
files before Rammel itself is available to otherwise do the same task. These
tools can be made obsolete by shipping the tangled sources of all webs alongside
the webs: further development occurs in the webs; initial build is already
bootstrapped. Shipping these C sources is identical to shipping other C (more
appropriately, Rammel) C sources. These remain whilst the rest of Rammel is
built up, particularly its renewed GNU Make build system.

#+begin_src makefile :tangle src/tools/Makefile
  $(if $(findstring "undefined",$(origin OUTPUT)), $(error "The variable OUTPUT was undefined!"))

  TANGLEOBJS=$(addprefix $(OUTPUT)/,$(addsuffix .o,notangle getline match modules modtrees strsave main errors columns))
  MARKUPOBJS=$(addprefix $(OUTPUT)/,$(addsuffix .o,markmain strsave markup errors getline columns))
  OBJS=$(TANGLEOBJS) $(MARKUPOBJS) $(OUTPUT)/nocond.o $(OUTPUT)/tie.o

  all: $(OUTPUT) $(addprefix $(OUTPUT)/,markup nocond nt tie)

  $(OUTPUT)/markup: $(MARKUPOBJS)
  	$(CC) -o$@ $(LDFLAGS) $^

  $(OUTPUT)/nt: $(TANGLEOBJS)
  	$(CC) -o$@ $(LDFLAGS) $^

  $(OUTPUT)/nocond: $(OUTPUT)/nocond.o
  	$(CC) -o$@ $(LDFLAGS) $^

  $(OUTPUT)/tie: $(OUTPUT)/tie.o
  	$(CC) -o$@ $(LDFLAGS) $^

  clean:
  	-$(RM) $(OBJS)

  clobber: clean
  	-$(RM) $(addprefix $(OUTPUT)/,markup nocond nt tie)

  $(OUTPUT)/columns.o:	columns.c columns.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ columns.c
  $(OUTPUT)/errors.o:	errors.c errors.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ errors.c
  $(OUTPUT)/getline.o: getline.c columns.h errors.h getline.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ getline.c
  $(OUTPUT)/main.o:	main.c columns.h errors.h modtrees.h modules.h notangle.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ main.c
  $(OUTPUT)/markmain.o:	markmain.c columns.h errors.h getline.h markup.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ markmain.c
  $(OUTPUT)/markup.o:	markup.c errors.h markup.h strsave.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ markup.c
  $(OUTPUT)/match.o:	match.c match.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ match.c
  $(OUTPUT)/modtrees.o:	modtrees.c errors.h modtrees.h modules.h strsave.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ modtrees.c
  $(OUTPUT)/modules.o:	modules.c columns.h errors.h modtrees.h modules.h strsave.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ modules.c
  $(OUTPUT)/nocond.o:	nocond.c
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ nocond.c
  $(OUTPUT)/notangle.o:	notangle.c errors.h getline.h modtrees.h modules.h notangle.h strsave.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ notangle.c
  $(OUTPUT)/strsave.o:	strsave.c errors.h strsave.h
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ strsave.c
  $(OUTPUT)/tie.o:	tie.c
  	$(CC) $(CFLAGS) -I$(OUTPUT) -o$@ tie.c
#+end_src

** DONE Vendored CII
CLOSED: [2026-05-03 Sun 01:14]
I've tried to clean up this makefile.

#+begin_src makefile :tangle src/cii/Makefile
  MAXALIGN=-DMAXALIGN=$(CIIMAXALIGN)

  OBJS=$(addprefix $(OUTPUT)/,$(addsuffix .o,arena array assert atom except fmt list mem seq str))

  all: $(OUTPUT)/libcii.so $(OUTPUT)/memchk.o

  $(OUTPUT)/libcii.so: $(OBJS)
  	$(AR) -rsc $@ $(OBJS)

  $(OUTPUT)/%.o: $(srcdir)/cii/src/%.c
  	$(CC) $(CFLAGS) -Iinclude $(MAXALIGN) $< -o $@

  clean:
  	-$(RM) $(OBJS)

  clobber:	clean
  	-$(RM) $(OUTPUT)/libcii$A $(OUTPUT)/*.o
#+end_src

** TODO Vendored Lua [2/3]
*** DONE 2.5.1
CLOSED: [2026-05-03 Sun 01:28]
This makefile is based upon the upstream.

#+begin_src makefile :tangle src/lua-2.5.1/makefile
  # CONFIGURATION
  # define (undefine) POPEN if your system (does not) support piped I/O
  # define (undefine) _POSIX_SOURCE if your system is (not) POSIX compliant
  # define (undefine) NOSTRERROR if your system does NOT have function "strerror"
  # (although this is ANSI, SunOS does not comply; so, add "-DNOSTRERROR" on SunOS)
  CONFIG = -DPOPEN -D_POSIX_SOURCE
  # Compilation parameters
  CC = gcc
  CFLAGS = $(CONFIG) -Wall -Wmissing-prototypes -Wshadow -ansi -O2 -pedantic

  AR = ar
  ARFLAGS = rsc

  # Aplication modules
  LUAOBJS = $(addprefix $(OUTPUT)/,$(addsuffix .o,parser lex opcode hash table inout tree fallback luamem func undump))

  LIBOBJS = $(addprefix $(OUTPUT)/,iolib.o mathlib.o strlib.o)

  all : $(OUTPUT)/lua

  $(OUTPUT)/lua : $(OUTPUT)/lua.o $(OUTPUT)/liblua.so $(OUTPUT)/liblualib.so
  	$(CC) $(CFLAGS) -o $@ -I. -lm $^

  $(OUTPUT)/liblua.so : $(LUAOBJS)
  	$(AR) $(ARFLAGS) $@ $?

  $(OUTPUT)/liblualib.so : $(LIBOBJS)
  	$(AR) $(ARFLAGS) $@ $?

  $(OUTPUT)/liblua.so.1.0 : lua.o
  	$(LD) -o liblua.so.1.0 $(LDFLAGS) $(LUAOBJS)

  y.tab.c y.tab.h : lua.stx
  	yacc -d lua.stx -o $@

  parser.c : y.tab.c
  	sed -e 's/yy/luaY_/g' -e 's/malloc\.h/stdlib\.h/g' y.tab.c > parser.c

  parser.h : y.tab.h
  	sed -e 's/yy/luaY_/g' y.tab.h > parser.h

  clear	:
  	rm -f *.o
  	rm -f parser.c parser.h y.tab.c y.tab.h

  $(OUTPUT)/parser.o : parser.c parser.h
  	$(CC) -c $(CFLAGS) $(LDFLAGS) -I. -o $@ $<

  $(OUTPUT)/%.o : %.c
  	$(CC) -c $(CFLAGS) $(LDFLAGS) -I. -o $@ $<

  $(OUTPUT)/mathlib.o : mathlib.c lualib.h lua.h
  	$(CC) -c $(CFLAGS) $(LDFLAGS) -lm -I. -o $@ $<

#+end_src

The mathematics library for Lua 2.5.1 is not compiling properly; there are missing symbols.

*** DONE 3.2.2
CLOSED: [2026-05-06 Wed 22:59]
With Lua 3.2.2 being very easy to compile, I haven't had to make any changes. However, I have removed the =co= target.

#+begin_src makefile :tangle src/lua-3.2.2/Makefile
  # makefile for lua hierarchy

  all clean klean:
  	$(MAKE) -C include $@
  	$(MAKE) -C src $@
  	$(MAKE) -C src/luac $@
  	$(MAKE) -C src/lib $@
  	$(MAKE) -C src/lua $@

  strip:
  	strip bin/lua*

#+end_src
*** TODO 5.5.0
